version: '3.9'

services:
  mlflow_example:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: ml_service:$USER
    container_name: ml_service_$USER
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8899:8890
    environment:
      - MLFLOW_TRACKING_URI=http://158.160.2.37:5000/
      - DEFAULT_RUN_ID=${DEFAULT_RUN_ID}
      - EVIDENTLY_URL=http://158.160.2.37:8000/
      - EVIDENTLY_PROJECT_ID=${EVIDENTLY_PROJECT_ID}
      - REFERENCE_DATA_PATH=/app/data/reference.csv
      - DRIFT_REPORT_INTERVAL_SECONDS=${DRIFT_REPORT_INTERVAL_SECONDS:-60}
      - DRIFT_WINDOW_SIZE=${DRIFT_WINDOW_SIZE:-100}
    command: uvicorn main:app --host 0.0.0.0 --port 8890 --reload
